# Copyright (C) 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# We have to use PRODUCT_PACKAGES (together with BUILD_PREBUILT) instead of
# PRODUCT_COPY_FILES to install the font files, so that the NOTICE file can
# get installed too.

PRODUCT_PACKAGES := \
    NotoColorEmoji.ttf \
    NotoNaskhArabic-Bold.ttf \
    NotoNaskhArabic.ttf \
    NotoNaskhArabicUI-Bold.ttf \
    NotoNaskhArabicUI.ttf \
    NotoSansAdlam-Regular.ttf \
    NotoSansAhom-Regular.otf \
    NotoSansAnatolianHieroglyphs-Regular.otf \
    NotoSansArmenian-Bold.otf \
    NotoSansArmenian-Medium.otf \
    NotoSansArmenian-Regular.otf \
    NotoSansAvestan.ttf \
    NotoSansBalinese.ttf \
    NotoSansBamum.ttf \
    NotoSansBassaVah-Regular.otf \
    NotoSansBatak.ttf \
    NotoSansBengali-Bold.otf \
    NotoSansBengali-Medium.otf \
    NotoSansBengali-Regular.otf \
    NotoSansBengaliUI-Bold.otf \
    NotoSansBengaliUI-Medium.otf \
    NotoSansBengaliUI-Regular.otf \
    NotoSansBhaiksuki-Regular.otf \
    NotoSansBrahmi.ttf \
    NotoSansBuginese.ttf \
    NotoSansBuhid.ttf \
    NotoSansCanadianAboriginal.ttf \
    NotoSansCarian.ttf \
    NotoSansChakma-Regular.otf \
    NotoSansCham-Bold.ttf \
    NotoSansCham.ttf \
    NotoSansCherokee-Regular.ttf \
    NotoSansCJKjp-Regular.otc \
    NotoSansCoptic.ttf \
    NotoSansCuneiform.ttf \
    NotoSansCypriot.ttf \
    NotoSansDeseret.ttf \
    NotoSansDevanagari-Bold.otf \
    NotoSansDevanagari-Medium.otf \
    NotoSansDevanagari-Regular.otf \
    NotoSansDevanagariUI-Bold.otf \
    NotoSansDevanagariUI-Medium.otf \
    NotoSansDevanagariUI-Regular.otf \
    NotoSansEgyptianHieroglyphs.ttf \
    NotoSansElbasan-Regular.otf \
    NotoSansEthiopic-Bold.ttf \
    NotoSansEthiopic.ttf \
    NotoSansGeorgian-Regular.ttf \
    NotoSansGlagolitic.ttf \
    NotoSansGothic.ttf \
    NotoSansGujarati-Bold.ttf \
    NotoSansGujarati.ttf \
    NotoSansGujaratiUI-Bold.ttf \
    NotoSansGujaratiUI.ttf \
    NotoSansGunjalaGondi-Regular.otf \
    NotoSansGurmukhi-Bold.ttf \
    NotoSansGurmukhi.ttf \
    NotoSansGurmukhiUI-Bold.ttf \
    NotoSansGurmukhiUI.ttf \
    NotoSansHanifiRohingya-Regular.otf \
    NotoSansHanunoo.ttf \
    NotoSansHatran-Regular.otf \
    NotoSansHebrew-Bold.ttf \
    NotoSansHebrew.ttf \
    NotoSansImperialAramaic.ttf \
    NotoSansInscriptionalPahlavi.ttf \
    NotoSansInscriptionalParthian.ttf \
    NotoSansJavanese-Regular.otf \
    NotoSansKaithi.ttf \
    NotoSansKannada-Bold.ttf \
    NotoSansKannada.ttf \
    NotoSansKannadaUI-Bold.ttf \
    NotoSansKannadaUI.ttf \
    NotoSansKayahLi.ttf \
    NotoSansKharoshthi.ttf \
    NotoSansKhmer-Regular.ttf \
    NotoSansKhmerUI-Bold.ttf \
    NotoSansKhmerUI.ttf \
    NotoSansKhojki-Regular.otf \
    NotoSansLao-Bold.ttf \
    NotoSansLao.ttf \
    NotoSansLaoUI-Bold.ttf \
    NotoSansLaoUI.ttf \
    NotoSansLepcha.ttf \
    NotoSansLimbu.ttf \
    NotoSansLinearA-Regular.otf \
    NotoSansLinearB.ttf \
    NotoSansLisu.ttf \
    NotoSansLycian.ttf \
    NotoSansLydian.ttf \
    NotoSansMalayalam-Bold.otf \
    NotoSansMalayalam-Medium.otf \
    NotoSansMalayalam-Regular.otf \
    NotoSansMalayalamUI-Bold.otf \
    NotoSansMalayalamUI-Medium.otf \
    NotoSansMalayalamUI-Regular.otf \
    NotoSansMandaic.ttf \
    NotoSansManichaean-Regular.otf \
    NotoSansMarchen-Regular.otf \
    NotoSansMasaramGondi-Regular.otf \
    NotoSansMeeteiMayek.ttf \
    NotoSansMeroitic-Regular.otf \
    NotoSansMiao-Regular.otf \
    NotoSansMongolian.ttf \
    NotoSansMro-Regular.otf \
    NotoSansMultani-Regular.otf \
    NotoSansMyanmar-Bold.otf \
    NotoSansMyanmar-Medium.otf \
    NotoSansMyanmar-Regular.otf \
    NotoSansMyanmarUI-Bold.otf \
    NotoSansMyanmarUI-Medium.otf \
    NotoSansMyanmarUI-Regular.otf \
    NotoSansNabataean-Regular.otf \
    NotoSansNewa-Regular.otf \
    NotoSansNewTaiLue.ttf \
    NotoSansNKo.ttf \
    NotoSansOgham.ttf \
    NotoSansOlChiki.ttf \
    NotoSansOldItalic.ttf \
    NotoSansOldNorthArabian-Regular.otf \
    NotoSansOldPermic-Regular.otf \
    NotoSansOldPersian.ttf \
    NotoSansOldSouthArabian.ttf \
    NotoSansOldTurkic.ttf \
    NotoSansOriya-Bold.ttf \
    NotoSansOriya.ttf \
    NotoSansOriyaUI-Bold.ttf \
    NotoSansOriyaUI.ttf \
    NotoSansOsage-Regular.ttf \
    NotoSansOsmanya.ttf \
    NotoSansPahawhHmong-Regular.otf \
    NotoSansPalmyrene-Regular.otf \
    NotoSansPauCinHau-Regular.otf \
    NotoSansPhagsPa.ttf \
    NotoSansPhoenician.ttf \
    NotoSansRejang.ttf \
    NotoSansRunic.ttf \
    NotoSansSamaritan.ttf \
    NotoSansSaurashtra.ttf \
    NotoSansSharada-Regular.otf \
    NotoSansShavian.ttf \
    NotoSansSinhala-Bold.otf \
    NotoSansSinhala-Medium.otf \
    NotoSansSinhala-Regular.otf \
    NotoSansSinhalaUI-Bold.otf \
    NotoSansSinhalaUI-Medium.otf \
    NotoSansSinhalaUI-Regular.otf \
    NotoSansSoraSompeng-Regular.otf \
    NotoSansSundanese.ttf \
    NotoSansSylotiNagri.ttf \
    NotoSansSymbols-Regular-Subsetted.ttf \
    NotoSansSymbols-Regular-Subsetted2.ttf \
    NotoSansSyriacEastern.ttf \
    NotoSansSyriacEstrangela.ttf \
    NotoSansSyriacWestern.ttf \
    NotoSansTagalog.ttf \
    NotoSansTagbanwa.ttf \
    NotoSansTaiLe.ttf \
    NotoSansTaiTham.ttf \
    NotoSansTaiViet.ttf \
    NotoSansTamil-Bold.otf \
    NotoSansTamil-Medium.otf \
    NotoSansTamil-Regular.otf \
    NotoSansTamilUI-Bold.otf \
    NotoSansTamilUI-Medium.otf \
    NotoSansTamilUI-Regular.otf \
    NotoSansTelugu-Bold.ttf \
    NotoSansTelugu.ttf \
    NotoSansTeluguUI-Bold.ttf \
    NotoSansTeluguUI.ttf \
    NotoSansThaana-Bold.ttf \
    NotoSansThaana.ttf \
    NotoSansThai-Bold.ttf \
    NotoSansThai.ttf \
    NotoSansThaiUI-Bold.ttf \
    NotoSansThaiUI.ttf \
    NotoSansTibetan-Bold.ttf \
    NotoSansTibetan.ttf \
    NotoSansTifinagh-Regular.otf \
    NotoSansUgaritic.ttf \
    NotoSansVai.ttf \
    NotoSansWancho-Regular.otf \
    NotoSansWarangCiti-Regular.otf \
    NotoSansYi.ttf \
    NotoSerif-Bold.ttf \
    NotoSerif-BoldItalic.ttf \
    NotoSerif-Italic.ttf \
    NotoSerif.ttf \
    NotoSerifArmenian-Bold.otf \
    NotoSerifArmenian-Regular.otf \
    NotoSerifBengali-Bold.ttf \
    NotoSerifBengali.ttf \
    NotoSerifCJKjp-Regular.otc \
    NotoSerifDevanagari-Bold.ttf \
    NotoSerifDevanagari.ttf \
    NotoSerifEthiopic-Bold.otf \
    NotoSerifEthiopic-Regular.otf \
    NotoSerifGeorgian-Regular.ttf \
    NotoSerifGujarati-Bold.ttf \
    NotoSerifGujarati.ttf \
    NotoSerifGurmukhi-Bold.otf \
    NotoSerifGurmukhi-Regular.otf \
    NotoSerifHebrew-Bold.ttf \
    NotoSerifHebrew-Regular.ttf \
    NotoSerifKannada-Bold.ttf \
    NotoSerifKannada.ttf \
    NotoSerifKhmer-Bold.otf \
    NotoSerifKhmer-Regular.otf \
    NotoSerifLao-Bold.ttf \
    NotoSerifLao.ttf \
    NotoSerifMalayalam-Bold.ttf \
    NotoSerifMalayalam.ttf \
    NotoSerifMyanmar-Bold.otf \
    NotoSerifMyanmar-Regular.otf \
    NotoSerifSinhala-Bold.otf \
    NotoSerifSinhala-Regular.otf \
    NotoSerifTamil-Bold.otf \
    NotoSerifTamil-Regular.otf \
    NotoSerifTelugu-Bold.ttf \
    NotoSerifTelugu.ttf \
    NotoSerifThai-Bold.ttf \
    NotoSerifThai.ttf
